### ISSUE TITLE
Webpack configuration issue

### ISSUE THREAD

**Issue by Tineth** [aykutaras/serverless-speech2speech#2]
Hi there, I seem to be getting an error and I feel that it has to do with the webpack configuration. I have highlighted the error in the picture attached. I was wondering if you could help me fix this error. 

![image](https://user-images.githubusercontent.com/48790783/54745591-c8bb4c00-4bc1-11e9-8d16-1a66c2fef7a2.png)

**Comment by aykutaras** [comment]
Hi @Tineth,

This issue now resolved with new version of webpack.config.js
